[package]
name = "rtsp_invitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sscanf = "0.2.1"
tokio = { version = "1.18.2", features = ["full"] }
md5 = "0.7.0"